[package]
name = "rinha-backend-rust-3"
version = "0.1.0"
edition = "2024"

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'thin'
debug = false
incremental = false
overflow-checks = false

[dependencies]
anyhow = "1.0"
axum = "0.8.4"
chrono = { version = "0.4", features = ["serde"] }
csv = "1.3.1"
procfs = "0.17.0"
reqwest = { version = "0.12", default-features = false }
rust_decimal = { version = "1.37.2", features = ["serde-float"] }
scc = "2.3.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.46", features = ["fs", "io-util", "rt-multi-thread"] }
