[workspace]
resolver = "2"
members = [
    "api",
    "worker"
]

[workspace.package]
version = "1.0.0"
edition = "2024"
rust-version = "1.88.0"

[workspace.dependencies]
anyhow = "1.0.98"
crossbeam = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.47.0", features = ["fs", "rt-multi-thread"] }
tokio-postgres = { version = "0.7.13", features = ["with-chrono-0_4"] }