services:
  api01: &api
    build:
      context: .
      dockerfile: docker/Dockerfile.api.x86_64-unknown-linux-musl
    hostname: api01
    networks:
      - payment-processor
      - backend
    depends_on:
      - worker
    environment:
      CHANNEL_THREADS: 5
      DATABASE_URL: postgresql://postgres:postgres@db:5432/db
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "10MB"
    volumes:
      - sockets:/tmp/sockets

  api02:
    <<: *api
    hostname: api02

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker.x86_64-unknown-linux-musl
    networks:
      - payment-processor
      - backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      CHANNEL_THREADS: 5
      WORKER_THREADS: 50
      DATABASE_URL: postgresql://postgres:postgres@db:5432/db
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "10MB"
    volumes:
      - sockets:/tmp/sockets

  nginx:
    image: nginx:latest
    volumes:
      - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/tmp/sockets
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '70MB'

  postgres:
    image: postgres:latest
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - ./assets/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./assets/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    command: postgres -c config_file=/docker-entrypoint-initdb.d/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '250MB'

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true

volumes:
  sockets: