services:
  api01: &api
    build:
      context: .
      dockerfile: docker/Dockerfile.api.x86_64-unknown-linux-musl
    hostname: api01
    networks:
      - payment-processor
      - backend
    depends_on:
      - worker
    environment:
      BACKOFF_CHANNEL: 5
      CHANNEL_THREADS: 2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"
    volumes:
      - sockets:/tmp/sockets
      - storage:/tmp/storage

  api02:
    <<: *api
    hostname: api02

  api03:
    <<: *api
    hostname: api03

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker.x86_64-unknown-linux-musl
    networks:
      - payment-processor
      - backend
    environment:
      CHANNEL_THREADS: 6
      WORKER_THREADS: 16
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.85"
          memory: "60MB"
    volumes:
      - sockets:/tmp/sockets
      - storage:/tmp/storage

  nginx:
    image: nginx:latest
    volumes:
      - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/tmp/sockets
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '20MB'

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true

volumes:
  sockets:
  storage: