FROM rust:1.88 AS builder
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install -y podman iptables qemu-kvm 
RUN podman machine init
RUN podman machine start
RUN rustup target add x86_64-unknown-linux-musl
RUN cargo install cross
RUN RUSTFLAGS='-Clink-arg=-Wl,-Bstatic -Clink-arg=-lc' cross build --bin api --release --target x86_64-unknown-linux-musl

FROM scratch
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/api .
CMD ["./api"]