services:
  api01: &api
    build:
      context: .
      dockerfile: docker/Dockerfile.api.x86_64-unknown-linux-musl
    hostname: api01
    networks:
      - payment-processor
      - backend
    depends_on:
      - worker
    environment:
      DATABASE_URL: http://influxdb:8086
      BACKOFF_CHANNEL: 5
      CHANNEL_THREADS: 2
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "20MB"
    volumes:
      - sockets:/tmp/sockets

  api02:
    <<: *api
    hostname: api02

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.worker.x86_64-unknown-linux-musl
    networks:
      - payment-processor
      - backend
    depends_on:
      influxdb:
        condition: service_healthy
    environment:
      DATABASE_URL: http://influxdb:8086
      CHANNEL_THREADS: 4
      WORKER_THREADS: 2
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "60MB"
    volumes:
      - sockets:/tmp/sockets

  nginx:
    image: nginx:latest
    volumes:
      - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/tmp/sockets
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '20MB'

  influxdb:
    image: influxdb:latest
    hostname: influxdb
    volumes:
      - ./assets/influxdb.conf:/etc/influxdb/influxdb.conf:ro
    ports:
      - "8086:8086"
    networks:
      - backend
    healthcheck:
      test: "curl -f http://influxdb:8086/ping"
      interval: 5s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '230MB'

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true

volumes:
  sockets: