services:
  api01: &api
    build: .
    hostname: api01
    networks:
      - payment-processor
      - backend
    expose:
      - 8080
    environment:
      NODE: 1
      TCP_LISTEN: "0.0.0.0:8080"
      WORKER_MAX_THREADS: 15000
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "125MB"
        # reservations:
        #   cpus: "0.35"
        #   memory: "125MB"
    volumes:
      - api:/tmp

  api02:
    <<: *api
    hostname: api02
    expose:
      - 8081
    environment:
      NODE: 2
      TCP_LISTEN: "0.0.0.0:8081"
      WORKER_MAX_THREADS: 15000
      PAYMENT_PROCESSOR_URL_DEFAULT: http://payment-processor-default:8080
      PAYMENT_PROCESSOR_URL_FALLBACK: http://payment-processor-fallback:8080

  nginx:
    image: nginx:latest
    volumes:
      - ./assets/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: '120MB'
        # reservations:
        #   cpus: '0.8'
        #   memory: '120MB'

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    external: true

volumes:
  api: