[package]
name = "worker"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'thin'
debug = false
incremental = false
overflow-checks = false

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true, features = ["serde"] }
crossbeam = { workspace = true }
reqwest = { version = "0.12", default-features = false }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { version = "1.47.0", features = ["macros", "fs", "rt-multi-thread"] }
tokio-postgres = { workspace = true }