[package]
name = "api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[profile.release]
opt-level = 3
codegen-units = 1
panic = 'abort'
lto = 'thin'
debug = false
incremental = false
overflow-checks = false

[dependencies]
anyhow = { workspace = true }
axum = "0.8.4"
chrono = { workspace = true }
crossbeam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }