name: CI Test K6

on:
  push:
    branches:
      - master

jobs:
  ci-k6-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up k6
        uses: grafana/setup-k6-action@v1
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run make ci-k6-test
        run: make ci-k6-test
